
# 1
SELECT * FROM CITY WHERE CountryCode = 'USA' AND POPULATION > 100000;

# 2
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 120000;

# 3
SELECT * FROM CITY;

# 4
SELECT * FROM CITY WHERE ID = 1661;

# 5
SELECT * FROM CITY WHERE COUNTRYCODE = 'JPN';

# 6
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'JPN';

# 7
SELECT CITY, STATE FROM STATION;

# 8
SELECT DISTINCT CITY FROM STATION WHERE ID % 2 = 0;

# 9
SELECT ((SELECT COUNT(CITY) FROM STATION) - (SELECT COUNT(DISTINCT CITY) FROM STATION));

# 10
SELECT CONCAT(CITY, ' ', LENGTH(CITY)) FROM STATION
ORDER BY LENGTH(CITY), CITY
LIMIT 1;

SELECT CONCAT(CITY, ' ', LENGTH(CITY)) FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY
LIMIT 1;