# 11
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '^[aeiou]';

# 12
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '[aeiou]$';

# 13
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '^[aeiou].*[aeiou]$';

# 14
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '^[^aeiou]';

# 15
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '[^aeiou]$';

# 16
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '^[^aeiou]|[^aeiou]$';

# 17
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '^[^aeiou].*[^aeiou]$';

# 18
SELECT NAME FROM STUDENTS WHERE MARKS > 75 ORDER BY RIGHT(NAME, 3), ID;

# 19
SELECT NAME FROM EMPLOYEE ORDER BY NAME ASC;

# 20
SELECT name FROM EMPLOYEE WHERE SALARY > 2000 AND MONTHS < 10 ORDER BY EMPLOYEE_ID ASC;